version: '3'

services:
  my_blog_admin_api:
    image: hub.develobeer.blog/admin-api:${TAG}

    volumes:
      - /static:/root/www

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "8888:8080"